name: rmp2SF
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.9
  - numpy
  - pytorch
  - torchvision
  - pip
  - gym
  - pip:
    - catkin_pkg
    - scipy
    - tqdm
    - matplotlib
    - tensorflow-cpu
    - ray[rllib]
    - ray[debug]
    - tensorflow-probability
    - urdf-parser-py
    - torchviz
    - natsort
    - pybullet
    - pyyaml